rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
gemfile:
  - gemfiles/activerecord_2.3.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/activerecord-2.3.gemfile
script: "rake spec"
